Update patch set 1
Patch Set 1: Code-Review-1

meh, false alarm:

 2019-12-04 11:49:29.652612 | w | [ 24%] Building CXX object CMakeFiles/yangschema.dir/src/yang_schema.cpp.o
2019-12-04 11:49:29.652904 | w | /home/ci/build/build/netconf-cli-custom/src/yang_schema.cpp: In instantiation of 'YangSchema::enumValues(const schemaPath_&, const ModuleNodePair&) const::<lambda(const S_Type_Enum&)>::<lambda(auto:2)> [with auto:2 = std::shared_ptr<libyang::Iffeature>]':
2019-12-04 11:49:29.653248 | w | /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/bits/predefined_ops.h:351:12:   required from 'bool __gnu_cxx::__ops::_Iter_negate<_Predicate>::operator()(_Iterator) [with _Iterator = __gnu_cxx::__normal_iterator<std::shared_ptr<libyang::Iffeature>*, std::vector<std::shared_ptr<libyang::Iffeature> > >; _Predicate = YangSchema::enumValues(const schemaPath_&, const ModuleNodePair&) const::<lambda(const S_Type_Enum&)>::<lambda(auto:2)>]'
2019-12-04 11:49:29.653659 | w | /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/bits/stl_algo.h:120:14:   required from '_RandomAccessIterator std::__find_if(_RandomAccessIterator, _RandomAccessIterator, _Predicate, std::random_access_iterator_tag) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::shared_ptr<libyang::Iffeature>*, std::vector<std::shared_ptr<libyang::Iffeature> > >; _Predicate = __gnu_cxx::__ops::_Iter_negate<YangSchema::enumValues(const schemaPath_&, const ModuleNodePair&) const::<lambda(const S_Type_Enum&)>::<lambda(auto:2)> >]'
2019-12-04 11:49:29.654015 | w | /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/bits/stl_algo.h:171:28:   required from '_InputIterator std::__find_if_not(_InputIterator, _InputIterator, _Predicate) [with _InputIterator = __gnu_cxx::__normal_iterator<std::shared_ptr<libyang::Iffeature>*, std::vector<std::shared_ptr<libyang::Iffeature> > >; _Predicate = __gnu_cxx::__ops::_Iter_pred<YangSchema::enumValues(const schemaPath_&, const ModuleNodePair&) const::<lambda(const S_Type_Enum&)>::<lambda(auto:2)> >]'
2019-12-04 11:49:29.654354 | w | /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/bits/stl_algo.h:566:32:   required from '_IIter std::find_if_not(_IIter, _IIter, _Predicate) [with _IIter = __gnu_cxx::__normal_iterator<std::shared_ptr<libyang::Iffeature>*, std::vector<std::shared_ptr<libyang::Iffeature> > >; _Predicate = YangSchema::enumValues(const schemaPath_&, const ModuleNodePair&) const::<lambda(const S_Type_Enum&)>::<lambda(auto:2)>]'
2019-12-04 11:49:29.654652 | w | /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/bits/stl_algo.h:509:40:   required from 'bool std::all_of(_IIter, _IIter, _Predicate) [with _IIter = __gnu_cxx::__normal_iterator<std::shared_ptr<libyang::Iffeature>*, std::vector<std::shared_ptr<libyang::Iffeature> > >; _Predicate = YangSchema::enumValues(const schemaPath_&, const ModuleNodePair&) const::<lambda(const S_Type_Enum&)>::<lambda(auto:2)>]'
2019-12-04 11:49:29.654732 | w | /home/ci/build/build/netconf-cli-custom/src/yang_schema.cpp:141:101:   required from here
2019-12-04 11:49:29.654862 | w | /home/ci/build/build/netconf-cli-custom/src/yang_schema.cpp:141:91: error: 'using element_type = class libyang::Iffeature' {aka 'class libyang::Iffeature'} has no member named 'value'
2019-12-04 11:49:29.654942 | w |          return std::all_of(iffeatures.begin(), iffeatures.end(), [](auto it) { return it->value(); });
2019-12-04 11:49:29.655018 | w |                                                                                        ~~~~^~~~~
2019-12-04 11:49:29.655123 | w | In file included from /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:71,
2019-12-04 11:49:29.655229 | w |                  from /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/bits/char_traits.h:39,
2019-12-04 11:49:29.655370 | w |                  from /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/ios:40,
2019-12-04 11:49:29.655472 | w |                  from /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/ostream:38,
2019-12-04 11:49:29.655576 | w |                  from /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/iostream:39,
2019-12-04 11:49:29.655678 | w |                  from /home/ci/build/per-package/netconf-cli/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/libyang/Libyang.hpp:18,
2019-12-04 11:49:29.655761 | w |                  from /home/ci/build/build/netconf-cli-custom/src/yang_schema.cpp:9:
2019-12-04 11:49:29.656078 | w | /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/bits/predefined_ops.h: In instantiation of 'bool __gnu_cxx::__ops::_Iter_negate<_Predicate>::operator()(_Iterator) [with _Iterator = __gnu_cxx::__normal_iterator<std::shared_ptr<libyang::Iffeature>*, std::vector<std::shared_ptr<libyang::Iffeature> > >; _Predicate = YangSchema::enumValues(const schemaPath_&, const ModuleNodePair&) const::<lambda(const S_Type_Enum&)>::<lambda(auto:2)>]':
2019-12-04 11:49:29.656479 | w | /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/bits/stl_algo.h:120:14:   required from '_RandomAccessIterator std::__find_if(_RandomAccessIterator, _RandomAccessIterator, _Predicate, std::random_access_iterator_tag) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::shared_ptr<libyang::Iffeature>*, std::vector<std::shared_ptr<libyang::Iffeature> > >; _Predicate = __gnu_cxx::__ops::_Iter_negate<YangSchema::enumValues(const schemaPath_&, const ModuleNodePair&) const::<lambda(const S_Type_Enum&)>::<lambda(auto:2)> >]'
2019-12-04 11:49:29.656839 | w | /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/bits/stl_algo.h:171:28:   required from '_InputIterator std::__find_if_not(_InputIterator, _InputIterator, _Predicate) [with _InputIterator = __gnu_cxx::__normal_iterator<std::shared_ptr<libyang::Iffeature>*, std::vector<std::shared_ptr<libyang::Iffeature> > >; _Predicate = __gnu_cxx::__ops::_Iter_pred<YangSchema::enumValues(const schemaPath_&, const ModuleNodePair&) const::<lambda(const S_Type_Enum&)>::<lambda(auto:2)> >]'
2019-12-04 11:49:29.657144 | w | /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/bits/stl_algo.h:566:32:   required from '_IIter std::find_if_not(_IIter, _IIter, _Predicate) [with _IIter = __gnu_cxx::__normal_iterator<std::shared_ptr<libyang::Iffeature>*, std::vector<std::shared_ptr<libyang::Iffeature> > >; _Predicate = YangSchema::enumValues(const schemaPath_&, const ModuleNodePair&) const::<lambda(const S_Type_Enum&)>::<lambda(auto:2)>]'
2019-12-04 11:49:29.657501 | w | /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/bits/stl_algo.h:509:40:   required from 'bool std::all_of(_IIter, _IIter, _Predicate) [with _IIter = __gnu_cxx::__normal_iterator<std::shared_ptr<libyang::Iffeature>*, std::vector<std::shared_ptr<libyang::Iffeature> > >; _Predicate = YangSchema::enumValues(const schemaPath_&, const ModuleNodePair&) const::<lambda(const S_Type_Enum&)>::<lambda(auto:2)>]'
2019-12-04 11:49:29.657578 | w | /home/ci/build/build/netconf-cli-custom/src/yang_schema.cpp:141:101:   required from here
2019-12-04 11:49:29.657713 | w | /home/ci/build/per-package/netconf-cli/host/opt/ext-toolchain/arm-linux-gnueabihf/include/c++/8.3.0/bits/predefined_ops.h:351:12: error: void value not ignored as it ought to be
2019-12-04 11:49:29.657752 | w |   { return !bool(_M_pred(*__it)); }
2019-12-04 11:49:29.657789 | w |             ^~~~~~~~~~~~~~~~~~~~
2019-12-04 11:49:29.657873 | w | make[4]: *** [CMakeFiles/yangschema.dir/build.make:63: CMakeFiles/yangschema.dir/src/yang_schema.cpp.o] Error 1
2019-12-04 11:49:29.657936 | w | make[3]: *** [CMakeFiles/Makefile2:211: CMakeFiles/yangschema.dir/all] Error 2
2019-12-04 11:49:29.657983 | w | make[3]: *** Waiting for unfinished jobs....

Patch-set: 1
Reviewer: Gerrit User 1000000 <1000000@e32f8df8-3db0-4f76-a6c6-fe9d6e69dd68>
Label: Code-Review=-1