tools: fix eeprom serialization of MAC addresses
There was a typo in the source code which resulted in the following
error when trying to write a MAC address containing 0x80 or higher byte:

  $ python3 czechlight-blob-onie-eeprom.py --model CL-sdn-dual-bidi-EDFA --serial "PGCL250349" --mac 00:11:17:01:01:90 --vendor "PEI Genesis" --manufacturer "PEI Genesis" --part-no "PG-CL-SDN-dualBiDi" --country "CZ" --ftdi $(udevadm info --query=property --property=ID_SERIAL_SHORT --value /dev/ttyUSB*) --version "01" >> eeprom
  Traceback (most recent call last):
    File "/br2-external/tools/czechlight-blob-onie-eeprom.py", line 115, in <module>
      headers = generic(args.model, args.part_no, args.serial, args.mac, args.date, args.version, args.manufacturer, args.vendor, args.country) + \
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/br2-external/tools/czechlight-blob-onie-eeprom.py", line 71, in generic
      headers.append((TLV_MAC1, struct.pack('>7b', 6, *[int(x, 16) for x in mac_address.groups()])))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  struct.error: 'b' format requires -128 <= number <= 127

Docs [1] say, that we should use 'B' format for unsigned bytes.

[1] https://docs.python.org/3/library/struct.html

Fixes: 1141030a ("a tool for generating ONIE-ish EEPROM images")
Change-Id: I3c5a0b1f6b953836223541a16ec4733cea1a2e95